# Generated by Django 5.0.2 on 2024-03-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proto_dmd_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='markdowncontent',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
